# Generated by Django 4.2.6 on 2023-10-16 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish_time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
