# Generated by Django 4.2.6 on 2023-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_new_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
