# Generated by Django 4.2.7 on 2023-11-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_comment_options_replycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.GenericIPAddressField()),
            ],
        ),
    ]
