# Generated by Django 4.2.7 on 2023-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_countview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='summary_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='summary_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='summary_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
